# Generated by Django 4.1.7 on 2024-08-27 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator,
                            django.core.validators.MinValueValidator,
                        ],
                    ),
                ),
                ("comments", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
