# Generated by Django 4.1.7 on 2024-08-27 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books", "0001_initial"),
        ("book_reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_review",
                to="books.book",
            ),
        ),
    ]
